require_relative '../bundle/bundler/setup'

require 'shellwords'

require 'repla/test'
require Repla::Test::TEST_HELPER_FILE
require Repla::Test::REPLA_FILE

task :default => ['html:tests']

namespace :html do
  
  task :tests => [:clean_up]

  task :test_controller do
    controller_tests_file = File.join(File.dirname(__FILE__), "tc_controller.rb")
    ruby Shellwords.escape(controller_tests_file)
  end

  task :test_plugin => [:test_controller] do
    plugin_tests_file = File.join(File.dirname(__FILE__), "tc_plugin.rb")
    ruby Shellwords.escape(plugin_tests_file)
  end

  task :clean_up => [:test_plugin] do
    Repla::Test::Helper::quit
  end
end
