# A sample Gemfile
source "https://rubygems.org"
ruby '2.0.0'
gem "listen"
gem "webconsole"
gem "nio" # "nio" is a dependency of listen, before adding it explicitely here, new machines were getting a load error.